# Scraping URL 
GET  https://statusinvest.com.br/category/advancedsearchresultpaginated?search=%7B%7D&page=11&take=50&CategoryType=2 HTTP/1.1
Content-Type: application/json

###

# Backend proxy
GET  http://localhost:3000/api/proxy/ HTTP/1.1
Content-Type: application/json
